/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;

import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import crud.tambah;

/**
 *
 * @author ASUS
 */
public class data_barang1 extends javax.swing.JFrame {

    boolean drop = false;

    private Timer timer;

    koneksi db = new koneksi();
    DefaultTableModel table = new DefaultTableModel();
    String role;

    /**
     * Creates new form login
     */
    public data_barang1(String role) {
        initComponents();
         
        pn_hilang1.setVisible(drop);
        this.role = role;
        if(role.equals("staff")) {
            btn_databarang.setVisible(false);
            btn_laporan.setVisible(false);
            btn_karyawan.setVisible(false);
        }
        //resizeImage("C:\\Users\\ASUS\\Documents\\Ari\\JavaApplication13\\src\\image\\box.png", 60, 60, img_box, this);
        //resizeImage("C:\\Users\\ASUS\\Documents\\Ari\\JavaApplication13\\src\\image\\payment.png", 60, 60, img_transaksi2, this);
        //resizeImage("C:\\Users\\ASUS\\Documents\\Ari\\JavaApplication13\\src\\image\\box1.png", 60, 60, img_box1, this);
        //resizeImage("C:\\Users\\ASUS\\Documents\\Ari\\JavaApplication13\\src\\image\\laporan.png", 60, 60, img_laporan1, this);
        //resizeImage("C:\\Users\\ASUS\\Documents\\Ari\\JavaApplication13\\src\\image\\logout.png", 80, 80, img_logout, this);

        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        db.koneksi();
        setColumn();
        setRows();

        timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                showDayDateTime();
            }

        });

        timer.start();
    }

    private void showDayDateTime() {
        Calendar calendar = Calendar.getInstance();
        Date now = new Date();
        SimpleDateFormat formatHari = new SimpleDateFormat("EEEE", new Locale("in", "ID"));
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        String hari = formatHari.format(calendar.getTime());
        String dateTime = dateFormat.format(now);
        lb_date.setText(hari + ", " + dateTime);
    }

    public void setColumn() {
        table.addColumn("Kode Barang");
        table.addColumn("Nama Barang");
        table.addColumn("Stok Barang");
        table.addColumn("Harga");
        table.addColumn("Status");
        tabel_databarang1.setModel(table);
    }

    public void setRows() {
        table.setRowCount(0);
        ResultSet rs = db.ambilData("SELECT * FROM data_barang");
        try {
            while (rs.next()) {
                table.addRow(new Object[]{rs.getString("kode_barang"), rs.getString("nama_barang"), rs.getString("stok"), rs.getString("harga"), rs.getString("Status")});
            }
            tabel_databarang1.setModel(table);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    public static void resizeImage(String path, int width, int height, JLabel theLabel, JFrame theFrame) {
        try {
            BufferedImage bi = ImageIO.read(new File(path));
            Image i = bi.getScaledInstance(width, height, Image.SCALE_DEFAULT);
            ImageIcon ii = new ImageIcon(i);
            //JLabel label = new JLabel();
            theLabel.setIcon(ii);
            //theFrame.add(label);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Navbar = new javax.swing.JPanel();
        txt_navbar = new javax.swing.JLabel();
        lb_date = new javax.swing.JLabel();
        side_bar = new javax.swing.JPanel();
        home = new javax.swing.JLabel();
        btn_databarang = new project.CustomButtons();
        btn_transaksi = new project.CustomButtons();
        btn_karyawan = new project.CustomButtons();
        btn_laporan = new project.CustomButtons();
        btn_pemasukan = new project.CustomButtons();
        btn_pengeluaran = new project.CustomButtons();
        pn_hilang2 = new javax.swing.JPanel();
        pn_hilang1 = new javax.swing.JPanel();
        customButton4 = new project.CustomButtons();
        customButton5 = new project.CustomButtons();
        customButton6 = new project.CustomButtons();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_databarang1 = new project.CustomTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(java.awt.SystemColor.controlHighlight);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Navbar.setBackground(new java.awt.Color(25, 192, 236));
        Navbar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Navbar.setPreferredSize(new java.awt.Dimension(1340, 112));

        txt_navbar.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        txt_navbar.setForeground(new java.awt.Color(255, 255, 255));
        txt_navbar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_navbar.setText("DATA BARANG");

        lb_date.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb_date.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout NavbarLayout = new javax.swing.GroupLayout(Navbar);
        Navbar.setLayout(NavbarLayout);
        NavbarLayout.setHorizontalGroup(
            NavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavbarLayout.createSequentialGroup()
                .addContainerGap(224, Short.MAX_VALUE)
                .addComponent(txt_navbar, javax.swing.GroupLayout.PREFERRED_SIZE, 785, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lb_date, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        NavbarLayout.setVerticalGroup(
            NavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_navbar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(NavbarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_date, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(Navbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, 50));

        side_bar.setBackground(new java.awt.Color(255, 255, 255));
        side_bar.setMinimumSize(new java.awt.Dimension(150, 600));
        side_bar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home.png"))); // NOI18N
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });
        side_bar.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 138, -1));

        btn_databarang.setText("customButtons1");
        btn_databarang.setTheText("Data Barang");
        side_bar.add(btn_databarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 130, 30));

        btn_transaksi.setText("customButtons1");
        btn_transaksi.setTheText("Transaksi");
        side_bar.add(btn_transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 130, 30));

        btn_karyawan.setText("customButtons1");
        btn_karyawan.setTheText("Data Karyawan");
        side_bar.add(btn_karyawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 130, 30));

        btn_laporan.setText("customButtons1");
        btn_laporan.setTheText("Laporan");
        side_bar.add(btn_laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 130, 30));

        btn_pemasukan.setText("customButtons1");
        btn_pemasukan.setTheText("Pemasukan");
        side_bar.add(btn_pemasukan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 130, 30));

        btn_pengeluaran.setText("customButtons1");
        btn_pengeluaran.setTheText("Pengeluaran");
        side_bar.add(btn_pengeluaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 130, 30));

        pn_hilang2.setBackground(new java.awt.Color(255, 255, 255));

        pn_hilang1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pn_hilang1Layout = new javax.swing.GroupLayout(pn_hilang1);
        pn_hilang1.setLayout(pn_hilang1Layout);
        pn_hilang1Layout.setHorizontalGroup(
            pn_hilang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        pn_hilang1Layout.setVerticalGroup(
            pn_hilang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pn_hilang2Layout = new javax.swing.GroupLayout(pn_hilang2);
        pn_hilang2.setLayout(pn_hilang2Layout);
        pn_hilang2Layout.setHorizontalGroup(
            pn_hilang2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_hilang2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pn_hilang1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pn_hilang2Layout.setVerticalGroup(
            pn_hilang2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_hilang2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pn_hilang1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        side_bar.add(pn_hilang2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 130, -1));

        jPanel1.add(side_bar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 150, 830));

        customButton4.setText("customButton2");
        customButton4.setBackgroundColor(new java.awt.Color(255, 0, 51));
        customButton4.setBorderRadius(25);
        customButton4.setTextBold(0);
        customButton4.setTextColor(java.awt.Color.white);
        customButton4.setTheText("Hapus");
        customButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(customButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 570, 120, 40));

        customButton5.setText("customButton2");
        customButton5.setBackgroundColor(new java.awt.Color(25, 192, 236));
        customButton5.setBorderRadius(25);
        customButton5.setTextBold(0);
        customButton5.setTextColor(java.awt.Color.white);
        customButton5.setTheText("Tambah");
        customButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(customButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, 120, 40));

        customButton6.setText("customButton2");
        customButton6.setBackgroundColor(new java.awt.Color(25, 192, 236));
        customButton6.setBorderRadius(25);
        customButton6.setTextBold(0);
        customButton6.setTextColor(java.awt.Color.white);
        customButton6.setTheText("Edit");
        customButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(customButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 510, 120, 40));

        tabel_databarang1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_databarang1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                tabel_databarang1ComponentHidden(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_databarang1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 60, 1130, 360));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 704, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customButton5ActionPerformed
        // TODO add your handling code here:
        
        
        tambah_barang db1 = new tambah_barang(role);
        db1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_customButton5ActionPerformed

    private void customButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customButton6ActionPerformed
        // TODO add your handling code here:
       int row = tabel_databarang1.getSelectedRow();
        edit_barang db1 = new edit_barang(String.valueOf(tabel_databarang1.getValueAt(row, 0)));
        db1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_customButton6ActionPerformed

    private void customButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customButton4ActionPerformed
        // TODO add your handling code here:
        int row = tabel_databarang1.getSelectedRow();
        if (row != -1) {
            int confirm = JOptionPane.showConfirmDialog(null, "Apakah anda ingin hapus data ini?", "Peringatan", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (confirm == JOptionPane.YES_OPTION) {
                db.aksi("DELETE FROM data_barang WHERE kode_barang = '" + tabel_databarang1.getValueAt(row, 0) + "'");
                JOptionPane.showMessageDialog(null, "Berhasil Menghapus", "Pemberitahuan", JOptionPane.INFORMATION_MESSAGE);
                setRows();
            }
        }
    }//GEN-LAST:event_customButton4ActionPerformed

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        // TODO add your handling code here:
        Beranda db1 = new Beranda("owner");
        db1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homeMouseClicked

    private void bt_databarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_databarangMouseClicked
        // TODO add your handling code here:
        data_barang1 db1 = new data_barang1(role);
        db1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bt_databarangMouseClicked

    private void bt_databarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_databarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_databarangActionPerformed

    private void bt_transaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_transaksiMouseClicked
        // TODO add your handling code here:
        Transaksi db1 = new Transaksi(role);
        db1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bt_transaksiMouseClicked

    private void bt_transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_transaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_transaksiActionPerformed

    private void bt_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_logoutMouseClicked
        // TODO add your handling code here:
        login db1 = new login();
        db1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bt_logoutMouseClicked

    private void bt_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_logoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_logoutActionPerformed

    private void bt_laporan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_laporan1ActionPerformed
        // TODO add your handling code here:
        if (drop) {
            pn_hilang1.setVisible(drop);
            drop = false;

        } else {
            pn_hilang1.setVisible(drop);
            drop = true;
        }
    }//GEN-LAST:event_bt_laporan1ActionPerformed

    private void bt_pemasukan1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_pemasukan1MouseClicked
        // TODO add your handling code here:
        this.dispose();
        new Laporan(role).setVisible(true);
    }//GEN-LAST:event_bt_pemasukan1MouseClicked

    private void bt_pemasukan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_pemasukan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_pemasukan1ActionPerformed

    private void bt_pengeluaran1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_pengeluaran1MouseClicked
        // TODO add your handling code here:
        this.dispose();
        new pengeluaran(role).setVisible(true);
    }//GEN-LAST:event_bt_pengeluaran1MouseClicked

    private void bt_pengeluaran1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_pengeluaran1ActionPerformed
        // TODO add your handling code here:
        new pengeluaran(role).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bt_pengeluaran1ActionPerformed

    private void btn_karyawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_karyawanMouseClicked
        // TODO add your handling code here:
        data_karyawan db1 = new data_karyawan(role);
        db1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_karyawanMouseClicked

    private void btn_karyawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_karyawanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_karyawanActionPerformed

    private void tabel_databarang1ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tabel_databarang1ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_tabel_databarang1ComponentHidden

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(data_barang1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(data_barang1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(data_barang1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(data_barang1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new data_barang1("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Navbar;
    private project.CustomButtons btn_databarang;
    private project.CustomButtons btn_karyawan;
    private project.CustomButtons btn_laporan;
    private project.CustomButtons btn_pemasukan;
    private project.CustomButtons btn_pengeluaran;
    private project.CustomButtons btn_transaksi;
    private project.CustomButtons customButton4;
    private project.CustomButtons customButton5;
    private project.CustomButtons customButton6;
    private javax.swing.JLabel home;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_date;
    private javax.swing.JPanel pn_hilang1;
    private javax.swing.JPanel pn_hilang2;
    private javax.swing.JPanel side_bar;
    private project.CustomTable tabel_databarang1;
    private javax.swing.JLabel txt_navbar;
    // End of variables declaration//GEN-END:variables
}
