/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class login extends javax.swing.JFrame {
    koneksi db = new koneksi();
    String pass = "";
    String realPass = "";
    String temp = "";
    boolean showPass = false;
    String userRole;
    String role;

    /**
     * Creates new form login
     */
    public login() {
        String userRole;
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        db.koneksi();
        this.role = role;

    }
    
        public login (String role) {
        this.userRole = role;
        initComponents();
        
    }

    
    
    public static void resizeImage(int width, int height, JLabel theLabel, String path) {
        try {
            File file = new File ("src/image/" + path);
            BufferedImage bi = ImageIO.read(new File(path));
            Image i = bi.getScaledInstance(width, height, Image.SCALE_SMOOTH);
            ImageIcon ii = new ImageIcon(i);
            //JLabel label = new JLabel();
            theLabel.setIcon(ii);
            //theFrame.add(label);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txt_pw = new javax.swing.JTextField();
        btn_masuk = new javax.swing.JButton();
        txt_username = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        show_pass = new javax.swing.JCheckBox();
        logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(25, 192, 236));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_pw.setText("Password");
        txt_pw.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_pwFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_pwFocusLost(evt);
            }
        });
        txt_pw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pwActionPerformed(evt);
            }
        });
        txt_pw.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_pwKeyReleased(evt);
            }
        });
        jPanel2.add(txt_pw, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 350, 40));

        btn_masuk.setText("Masuk");
        btn_masuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_masukMouseClicked(evt);
            }
        });
        btn_masuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_masukActionPerformed(evt);
            }
        });
        jPanel2.add(btn_masuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 110, 30));

        txt_username.setText("Username");
        txt_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_usernameFocusLost(evt);
            }
        });
        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });
        jPanel2.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 350, 40));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Masukkan Akun Anda");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 65)); // NOI18N
        jLabel1.setText("Login");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 210, 90));
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 127, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("----------------------------------------------------------");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 340, -1));

        show_pass.setText("Show Password");
        show_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_passActionPerformed(evt);
            }
        });
        jPanel2.add(show_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 110, 20));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logolaundrym.jpg"))); // NOI18N
        jPanel2.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 90, 530, 380));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 1210, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1312, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code here:
        ResultSet rs = db.ambilData("SELECT * FROM login WHERE username = '" + txt_username.getText() + "'");
        try {
            if (rs.next()){
                JOptionPane.showMessageDialog(null, "Login Berhasil", "Pemberitahuan", JOptionPane.INFORMATION_MESSAGE);
                Beranda b = new Beranda(rs.getString("role"));
                    b.setVisible(true);
                    this.dispose();
            }
            
        } catch (Exception e) {
        }
        txt_pw.requestFocus();
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void txt_pwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pwActionPerformed
        // TODO add your handling code here: 
        ResultSet rs = db.ambilData("SELECT * FROM login WHERE username = '" + txt_username.getText() + "' AND password = '" + txt_pw.getText() + "'");
        try {
            if(rs.next()) {
                if(rs.getString("role").equals("owner")) {
                    Beranda b = new Beranda("owner");
                    b.setVisible(true);
                    JOptionPane.showMessageDialog(null, "Login Berhasil", "Pemberitahuan", JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                } else if(rs.getString("role").equals("staff")) {
                    Beranda b = new Beranda("staff");
                    b.setVisible(true);
                   
                    JOptionPane.showMessageDialog(null, "Login Berhasil", "Pemberitahuan", JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                }
                
            
            } else {
                JOptionPane.showMessageDialog(null, "Login Gagal, Periksa Username atau Password dan coba lagi", "Peringatan", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_txt_pwActionPerformed

    private void btn_masukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_masukActionPerformed
        // TODO add your handling code here:
        
        ResultSet rs = db.ambilData("SELECT * FROM login WHERE username = '" + txt_username.getText() + "' AND password = '" + txt_pw.getText() + "'");
        try {
            rs.next();
            if(rs.getString("role").equals("owner")) {
                Beranda b = new Beranda("owner");
                b.setVisible(true);
                JOptionPane.showMessageDialog(null, "Login Berhasil", "Pemberitahuan", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            } else if(rs.getString("role").equals("staff")) {
                Beranda b = new Beranda("staff");
                b.setVisible(true);
               
                JOptionPane.showMessageDialog(null, "Login Berhasil", "Pemberitahuan", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            
        }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btn_masukActionPerformed

    private void txt_usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_usernameFocusGained
        String username=txt_username.getText();
        if(username.equals("Username")){
            txt_username.setText("");
        }
    }//GEN-LAST:event_txt_usernameFocusGained

    private void txt_pwFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_pwFocusGained
        String pass=txt_pw.getText();
        if(pass.equals("Password")){
            txt_pw.setText("");
        }
    }//GEN-LAST:event_txt_pwFocusGained

    private void txt_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_usernameFocusLost
        String username=txt_username.getText();
        if(username.equals("")|username.equals("username")){
        txt_username.setText("Username");
    }
    }//GEN-LAST:event_txt_usernameFocusLost

    private void txt_pwFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_pwFocusLost
        String pass=txt_pw.getText();
        if(pass.equals("")|pass.equals("Password")){
        txt_pw.setText("Password");
    }
    }//GEN-LAST:event_txt_pwFocusLost

    private void txt_pwKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_pwKeyReleased
        // TODO add your handling code here:
        if(txt_pw.getText().equals("")) {
            realPass = "";
        } else {
            if(evt.getKeyCode() == 8){
                for(int i = 0; i < realPass.length() - 1; i++){
                temp += realPass.charAt(i);
                }
                realPass = temp;
            }
            realPass += String.valueOf(evt.getKeyChar());
            pass = txt_pw.getText();
            if(!showPass){
                txt_pw.setText("");
                for(int i = 0; i < pass.length(); i++){
                    txt_pw.setText(txt_pw.getText() + "*");
                }
            }
        }
    }//GEN-LAST:event_txt_pwKeyReleased

    private void show_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_passActionPerformed
        // TODO add your handling code here:
        if(show_pass.isSelected()) {
            showPass = true;
            txt_pw.setText(realPass);
        } else {
            showPass = false;
            txt_pw.setText("");
            for(int i = 0; i < pass.length(); i++){
                txt_pw.setText(txt_pw.getText() + "*");
            }
        }
    }//GEN-LAST:event_show_passActionPerformed

    private void btn_masukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_masukMouseClicked
        // TODO add your handling code here:
        Beranda db1 = new Beranda(role);
        db1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_masukMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_masuk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel logo;
    private javax.swing.JCheckBox show_pass;
    private javax.swing.JTextField txt_pw;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables

 
    }



    

