/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;

import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author ASUS
 */
public class pengeluaran extends javax.swing.JFrame {boolean drop = false;
    koneksi db = new koneksi();
    private Timer timer;
    String role;

    /**
     * Creates new form login
     */
    public pengeluaran(String role) {
        initComponents();
        pn_hilang.setVisible(drop);
        this.role = role;
        if(role.equals("staff")) {
            btn_databarang.setVisible(false);
          
           btn_karyawan.setVisible(false);
        }
        kode_pengeluaran();
        tanggal_pengeluaran.setText(LocalDate.now().toString());
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        

        
        timer = new Timer(1000,new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                        showDayDateTime();
            }
            });
            
        
       timer.start();
    }
    
    public void kode_pengeluaran() {
        try {
            ResultSet rs = db.ambilData("SELECT kode_pengeluaran FROM pengeluaran ORDER BY kode_pengeluaran DESC");
            if (rs.next()) {
                String TR = rs.getString("kode_pengeluaran");
                int angka = Integer.parseInt(TR.split("P")[1]);
                angka++;
                if (angka <= 9) {
                    kode_pengeluaran.setText("KP0" + angka);
                } else if (angka <= 99) {
                    kode_pengeluaran.setText("KP" + angka);
                }
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

   
    
    
 
    
    private void showDayDateTime() {
        Calendar calendar = Calendar.getInstance();     
        Date now = new Date();
        SimpleDateFormat formatHari = new SimpleDateFormat ("EEEE", new Locale("in", "ID"));
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        String hari = formatHari.format(calendar.getTime());
        String dateTime = dateFormat.format(now);
        lb_date.setText(hari+", "+dateTime);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Navbar = new javax.swing.JPanel();
        txt_navbar = new javax.swing.JLabel();
        lb_date = new javax.swing.JLabel();
        side_bar = new javax.swing.JPanel();
        home = new javax.swing.JLabel();
        pn_hilang = new javax.swing.JPanel();
        btn_databarang = new project.CustomButtons();
        btn_transaksi = new project.CustomButtons();
        btn_karyawan = new project.CustomButtons();
        btn_laporan = new project.CustomButtons();
        btn_pemasukan = new project.CustomButtons();
        btn_pengeluaran = new project.CustomButtons();
        pn_hilang1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        kode_pengeluaran = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jd_kodepengeluaran = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jd_jenispengeluaran = new javax.swing.JLabel();
        jenis_pengeluaran = new javax.swing.JComboBox<>();
        jPanel12 = new javax.swing.JPanel();
        jd_totalpengeluaran = new javax.swing.JLabel();
        total_pengeluaran = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        jd_keterangan = new javax.swing.JLabel();
        tanggal_pengeluaran = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        customButton4 = new project.CustomButtons();
        customButton5 = new project.CustomButtons();
        jScrollPane1 = new javax.swing.JScrollPane();
        keterangan = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Navbar.setBackground(new java.awt.Color(25, 192, 236));

        txt_navbar.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        txt_navbar.setForeground(new java.awt.Color(255, 255, 255));
        txt_navbar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_navbar.setText("PENGELUARAN");

        lb_date.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb_date.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout NavbarLayout = new javax.swing.GroupLayout(Navbar);
        Navbar.setLayout(NavbarLayout);
        NavbarLayout.setHorizontalGroup(
            NavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavbarLayout.createSequentialGroup()
                .addContainerGap(1058, Short.MAX_VALUE)
                .addComponent(lb_date, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NavbarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_navbar, javax.swing.GroupLayout.DEFAULT_SIZE, 1034, Short.MAX_VALUE)
                .addGap(300, 300, 300))
        );
        NavbarLayout.setVerticalGroup(
            NavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavbarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_navbar)
                .addGap(12, 12, 12)
                .addComponent(lb_date, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(Navbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 70));

        side_bar.setBackground(new java.awt.Color(255, 255, 255));
        side_bar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        home.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\Ari\\JavaApplication13\\src\\image\\home.png")); // NOI18N
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });
        side_bar.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, -1));

        pn_hilang.setBackground(new java.awt.Color(255, 255, 255));
        pn_hilang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        side_bar.add(pn_hilang, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 130, 80));

        btn_databarang.setText("customButtons1");
        btn_databarang.setTheText("Data Barang");
        side_bar.add(btn_databarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 130, 30));

        btn_transaksi.setText("customButtons1");
        btn_transaksi.setTheText("Transaksi");
        side_bar.add(btn_transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 130, 30));

        btn_karyawan.setText("customButtons1");
        btn_karyawan.setTheText("Data Karyawan");
        side_bar.add(btn_karyawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 130, 30));

        btn_laporan.setText("customButtons1");
        btn_laporan.setTheText("Laporan");
        side_bar.add(btn_laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 130, 30));

        btn_pemasukan.setText("customButtons1");
        btn_pemasukan.setTheText("Pemasukan");
        side_bar.add(btn_pemasukan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 130, 30));

        btn_pengeluaran.setText("customButtons1");
        btn_pengeluaran.setTheText("Pengeluaran");
        side_bar.add(btn_pengeluaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 130, 30));

        pn_hilang1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pn_hilang1Layout = new javax.swing.GroupLayout(pn_hilang1);
        pn_hilang1.setLayout(pn_hilang1Layout);
        pn_hilang1Layout.setHorizontalGroup(
            pn_hilang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        pn_hilang1Layout.setVerticalGroup(
            pn_hilang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        side_bar.add(pn_hilang1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 130, -1));

        jPanel1.add(side_bar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 150, 810));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kode_pengeluaran.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        kode_pengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kode_pengeluaranActionPerformed(evt);
            }
        });
        jPanel2.add(kode_pengeluaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 200, 40));

        jPanel9.setBackground(new java.awt.Color(25, 192, 236));

        jd_kodepengeluaran.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jd_kodepengeluaran.setForeground(new java.awt.Color(255, 255, 255));
        jd_kodepengeluaran.setText("Kode Pengeluaran");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jd_kodepengeluaran)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jd_kodepengeluaran, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 200, 30));

        jPanel11.setBackground(new java.awt.Color(25, 192, 236));

        jd_jenispengeluaran.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jd_jenispengeluaran.setForeground(new java.awt.Color(255, 255, 255));
        jd_jenispengeluaran.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jd_jenispengeluaran.setText("Jenis Pengeluaran");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jd_jenispengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(265, 265, 265))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jd_jenispengeluaran, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 230, 30));

        jenis_pengeluaran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Silahkan Pilih", "Listrik", "Air", "Bahan", "Gaji" }));
        jenis_pengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenis_pengeluaranActionPerformed(evt);
            }
        });
        jPanel2.add(jenis_pengeluaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 230, 30));

        jPanel12.setBackground(new java.awt.Color(25, 192, 236));

        jd_totalpengeluaran.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jd_totalpengeluaran.setForeground(new java.awt.Color(255, 255, 255));
        jd_totalpengeluaran.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jd_totalpengeluaran.setText("Total Pengeluaran");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jd_totalpengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jd_totalpengeluaran, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 230, 30));

        total_pengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_pengeluaranActionPerformed(evt);
            }
        });
        jPanel2.add(total_pengeluaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 230, 40));

        jPanel13.setBackground(new java.awt.Color(25, 192, 236));

        jd_keterangan.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jd_keterangan.setForeground(new java.awt.Color(255, 255, 255));
        jd_keterangan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jd_keterangan.setText("Keterangan");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jd_keterangan, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jd_keterangan, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 800, 30));

        tanggal_pengeluaran.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        tanggal_pengeluaran.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tanggal_pengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanggal_pengeluaranActionPerformed(evt);
            }
        });
        jPanel2.add(tanggal_pengeluaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 60, 220, 40));

        jPanel10.setBackground(new java.awt.Color(25, 192, 236));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Tanggal Pengeluaran");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 30, 220, 30));

        customButton4.setText("customButton2");
        customButton4.setBackgroundColor(new java.awt.Color(25, 192, 236));
        customButton4.setBorderRadius(25);
        customButton4.setTextBold(0);
        customButton4.setTextColor(java.awt.Color.white);
        customButton4.setTheText("Simpan");
        customButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(customButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 540, 160, 40));

        customButton5.setText("customButton2");
        customButton5.setBackgroundColor(new java.awt.Color(25, 192, 236));
        customButton5.setBorderRadius(25);
        customButton5.setTextBold(0);
        customButton5.setTextColor(java.awt.Color.white);
        customButton5.setTheText("Batal");
        customButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(customButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 540, 160, 40));

        keterangan.setColumns(20);
        keterangan.setRows(5);
        jScrollPane1.setViewportView(keterangan);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 800, 180));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 1190, 810));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kode_pengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kode_pengeluaranActionPerformed
        // TODO add your handling code here:
        ResultSet rs = db.ambilData("SELECT * FROM pengeluaran WHERE kode_pengeluaran = '" + kode_pengeluaran.getText() + "'");
        try { 
            
        }catch (Exception ex) {
            ex.printStackTrace();
        }
            
        
    }//GEN-LAST:event_kode_pengeluaranActionPerformed

    private void tanggal_pengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanggal_pengeluaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggal_pengeluaranActionPerformed

    private void jenis_pengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenis_pengeluaranActionPerformed
        // TODO add your handling code here:
        jenis_pengeluaran.requestFocus();
    }//GEN-LAST:event_jenis_pengeluaranActionPerformed

    private void total_pengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total_pengeluaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_total_pengeluaranActionPerformed

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        // TODO add your handling code here:
        Beranda db1 = new Beranda("owner");
        db1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homeMouseClicked

    private void bt_databarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_databarangMouseClicked
        // TODO add your handling code here:
        data_barang1 db1 = new data_barang1(role);
        db1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bt_databarangMouseClicked

    private void bt_databarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_databarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_databarangActionPerformed

    private void bt_transaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_transaksiMouseClicked
        // TODO add your handling code here:
        Transaksi db1 = new Transaksi(role);
        db1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bt_transaksiMouseClicked

    private void bt_transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_transaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_transaksiActionPerformed

    private void bt_laporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_laporanActionPerformed
        // TODO add your handling code here:
        if(drop) {
            pn_hilang.setVisible(drop);
            drop = false;

        }else {
            pn_hilang.setVisible(drop);
            drop = true;
        }
    }//GEN-LAST:event_bt_laporanActionPerformed

    private void bt_pemasukanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_pemasukanMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new Laporan(role).setVisible(true);
    }//GEN-LAST:event_bt_pemasukanMouseClicked

    private void bt_pemasukanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_pemasukanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_pemasukanActionPerformed

    private void bt_pengeluaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_pengeluaranMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new pengeluaran(role).setVisible(true);
    }//GEN-LAST:event_bt_pengeluaranMouseClicked

    private void bt_pengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_pengeluaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_pengeluaranActionPerformed

    private void bt_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_logoutMouseClicked
        // TODO add your handling code here:
        login db1 = new login();
        db1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bt_logoutMouseClicked

    private void bt_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_logoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_logoutActionPerformed

    private void customButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customButton4ActionPerformed
        // TODO add your handling code here:
        db.aksi("INSERT INTO pengeluaran (kode_pengeluaran, tanggal, jenis_pengeluaran, total_pengeluaran, keterangan) VALUES ('" + kode_pengeluaran.getText() + "','"+ tanggal_pengeluaran.getText() +"', '" + jenis_pengeluaran.getSelectedItem()+ "', '" + total_pengeluaran.getText() + "', '" + keterangan.getText() + "')");
        JOptionPane.showMessageDialog(null, "Tambah Berhasil", "Pemberitahuan", JOptionPane.INFORMATION_MESSAGE);
        tabel_pengeluaran db1 = new tabel_pengeluaran(role);
        db1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_customButton4ActionPerformed

    private void customButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customButton5ActionPerformed
        // TODO add your handling code here:
        tabel_pengeluaran db1 = new tabel_pengeluaran(role);
        db1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_customButton5ActionPerformed

    private void btn_karyawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_karyawanMouseClicked
        // TODO add your handling code here:
        data_karyawan db1 = new data_karyawan(role);
        db1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_karyawanMouseClicked

    private void btn_karyawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_karyawanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_karyawanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pengeluaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pengeluaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pengeluaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pengeluaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pengeluaran("").setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Navbar;
    private project.CustomButtons btn_databarang;
    private project.CustomButtons btn_karyawan;
    private project.CustomButtons btn_laporan;
    private project.CustomButtons btn_pemasukan;
    private project.CustomButtons btn_pengeluaran;
    private project.CustomButtons btn_transaksi;
    private project.CustomButtons customButton4;
    private project.CustomButtons customButton5;
    private javax.swing.JLabel home;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jd_jenispengeluaran;
    private javax.swing.JLabel jd_keterangan;
    private javax.swing.JLabel jd_kodepengeluaran;
    private javax.swing.JLabel jd_totalpengeluaran;
    private javax.swing.JComboBox<String> jenis_pengeluaran;
    private javax.swing.JTextArea keterangan;
    private javax.swing.JTextField kode_pengeluaran;
    private javax.swing.JLabel lb_date;
    private javax.swing.JPanel pn_hilang;
    private javax.swing.JPanel pn_hilang1;
    private javax.swing.JPanel side_bar;
    private javax.swing.JTextField tanggal_pengeluaran;
    private javax.swing.JTextField total_pengeluaran;
    private javax.swing.JLabel txt_navbar;
    // End of variables declaration//GEN-END:variables

    private void execute() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
