/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;

import java.sql.ResultSet;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class tabel_layanan extends javax.swing.JFrame {boolean drop = false;
String role;
 
DefaultTableModel table = new DefaultTableModel();
koneksi db = new koneksi();

    /**
     * Creates new form nambah_karyawan
     */
    public tabel_layanan(String role) {
        initComponents();
        this.role = role;
        db.koneksi();
        setColumn(); 
        setRows();
         this.setExtendedState(JFrame.MAXIMIZED_BOTH);
         //pn_hilang1.setVisible(drop);
    }
    
    public String changeToNum(String num) {
        String result = "";
        for(int i = 0; i < num.replace('.', 'a').split("a").length; i++) {
            result += num.replace('.', 'a').split("a")[i];
        }
        return result;
    }
    
    public String changeToRp(String num) {
        NumberFormat nf = NumberFormat.getInstance(new Locale("id", "ID"));
        return "Rp. " + nf.format(Double.parseDouble(num));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    public void setColumn() {
        table.addColumn("id layanan");
        table.addColumn("Jenis Layanan");
        table.addColumn("Nama Layanan");
        table.addColumn("Harga Layanan");
        table.addColumn("Tanggal Layanan");
        tabel_layanan.setModel(table);
    }
    
    
    
    
    public void setRows() {
        table.setRowCount(0);
//        tabel_databarang1.setModel(table);
        ResultSet rs = db.ambilData("SELECT * FROM data_layanan");
        try {
            while (rs.next()) {
                table.addRow(new Object[]{rs.getString("id_layanan"),rs.getString("jenis_layanan"), rs.getString("nama_layanan"), rs.getString("harga_layanan"), rs.getString("tgl_layanan")});
            }
            tabel_layanan.setModel(table);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelGradient2 = new pallette.JPanelGradient();
        txt_navbar = new javax.swing.JLabel();
        lb_date = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel_layanan = new project.CustomTable();
        tambah_karyawan = new project.CustomButtons();
        kembali = new project.CustomButtons();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelGradient2.setColorEnd(new java.awt.Color(25, 192, 236));
        jPanelGradient2.setColorStart(new java.awt.Color(25, 192, 236));
        jPanelGradient2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_navbar.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        txt_navbar.setForeground(new java.awt.Color(255, 255, 255));
        txt_navbar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_navbar.setText("DATA LAYANAN");
        jPanelGradient2.add(txt_navbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 892, 60));

        lb_date.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lb_date.setForeground(new java.awt.Color(255, 255, 255));
        jPanelGradient2.add(lb_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 20, 276, 36));

        jPanel1.add(jPanelGradient2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, 60));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabel_layanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabel_layanan);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 1240, 550));

        tambah_karyawan.setForeground(new java.awt.Color(255, 255, 255));
        tambah_karyawan.setText("Tambah");
        tambah_karyawan.setBackgroundColor(new java.awt.Color(255, 0, 51));
        tambah_karyawan.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        tambah_karyawan.setName("Edit"); // NOI18N
        tambah_karyawan.setTextColor(java.awt.Color.white);
        tambah_karyawan.setTheText("Hapus");
        tambah_karyawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambah_karyawanActionPerformed(evt);
            }
        });
        jPanel2.add(tambah_karyawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 30, 110, 31));

        kembali.setForeground(new java.awt.Color(255, 255, 255));
        kembali.setBackgroundColor(new java.awt.Color(25, 192, 236));
        kembali.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        kembali.setLabel("Kembali");
        kembali.setName("Data jenis Laundry\n"); // NOI18N
        kembali.setTextColor(java.awt.Color.white);
        kembali.setTheText("Kembali");
        kembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kembaliMouseClicked(evt);
            }
        });
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });
        jPanel2.add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 110, 31));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1340, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tambah_karyawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambah_karyawanActionPerformed
        // TODO add your handling code here:
          int row = tabel_layanan.getSelectedRow();
        if (row != -1) {
            int confirm = JOptionPane.showConfirmDialog(null, "Apakah anda ingin hapus data ini?", "Peringatan", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (confirm == JOptionPane.YES_OPTION) {
                db.aksi("DELETE FROM data_layanan WHERE id_layanan = '" + tabel_layanan.getValueAt(row, 0) + "'");
                JOptionPane.showMessageDialog(null, "Berhasil Menghapus", "Pemberitahuan", JOptionPane.INFORMATION_MESSAGE);
                setRows();
            }
        }
        
    }//GEN-LAST:event_tambah_karyawanActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kembaliActionPerformed

    private void kembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kembaliMouseClicked
        // TODO add your handling code here:
        Transaksi db1 = new Transaksi(role);
        db1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_kembaliMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tabel_layanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tabel_layanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tabel_layanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tabel_layanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tabel_layanan("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private pallette.JPanelGradient jPanelGradient2;
    private javax.swing.JScrollPane jScrollPane2;
    private project.CustomButtons kembali;
    private javax.swing.JLabel lb_date;
    private project.CustomTable tabel_layanan;
    private project.CustomButtons tambah_karyawan;
    private javax.swing.JLabel txt_navbar;
    // End of variables declaration//GEN-END:variables
}
