/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package lala;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import log.login;
import project.koneksi;
import utama.defaultform;

/**
 *
 * @author ASUS
 */
public class data_karyawan extends javax.swing.JPanel {
    koneksi db = new koneksi();
    DefaultTableModel model = new DefaultTableModel();
    String role;

    /**
     * Creates new form data_karyawan
     */
    public data_karyawan() {
        initComponents();
        this.role = role;
    addcoloum();
        Bariss();
        
        
    }
    
    public void addcoloum(){
        model.setColumnCount(0);
        model.addColumn("Nama");
        model.addColumn("email");
        model.addColumn("Telepon");
        model.addColumn("Alamat");
        model.addColumn("username");
        model.addColumn("Password");
        model.addColumn("Kelamin");
        model.addColumn("Role");
        tabel_data.setModel(model);
        
    }
    
    public void Bariss(){
        model.setRowCount(0);
        ResultSet hasil = db.ambilData("SELECT * FROM login");
        try {
            while(hasil.next()) {
                model.addRow(new Object[]
                {   //hasil.getString("id_laporan"),
                    hasil.getString("nama_pengguna"),
                    hasil.getString("email"),
                    hasil.getString("telepon"),
                    hasil.getString("alamat"),
                    hasil.getString("username"),
                    hasil.getString("password"),
                    hasil.getString("kelamin"),
                    hasil.getString("role")});
            }
             tabel_data.setModel(model);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        data_karyawan = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_data = new project.CustomTable();
        hapus = new project.CustomButtons();
        nambah_karyawan = new project.CustomButtons();

        data_karyawan.setBackground(new java.awt.Color(255, 255, 255));
        data_karyawan.setPreferredSize(new java.awt.Dimension(1190, 640));
        data_karyawan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabel_data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabel_data);

        data_karyawan.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1110, 490));

        hapus.setForeground(new java.awt.Color(255, 255, 255));
        hapus.setText("Data jenis Laundry");
        hapus.setBackgroundColor(new java.awt.Color(255, 0, 51));
        hapus.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        hapus.setName("Data jenis Laundry\n"); // NOI18N
        hapus.setTextColor(java.awt.Color.white);
        hapus.setTheText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        data_karyawan.add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 20, 120, 30));

        nambah_karyawan.setForeground(new java.awt.Color(255, 255, 255));
        nambah_karyawan.setText("Data jenis Laundry");
        nambah_karyawan.setBackgroundColor(new java.awt.Color(25, 192, 236));
        nambah_karyawan.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        nambah_karyawan.setName("Data jenis Laundry\n"); // NOI18N
        nambah_karyawan.setTextColor(java.awt.Color.white);
        nambah_karyawan.setTheText("Tambah");
        nambah_karyawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nambah_karyawanActionPerformed(evt);
            }
        });
        data_karyawan.add(nambah_karyawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 20, 120, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(data_karyawan, javax.swing.GroupLayout.PREFERRED_SIZE, 1136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(data_karyawan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        int row = tabel_data.getSelectedRow();
        if (row != -1) {
            int confirm = JOptionPane.showConfirmDialog(null, "Apakah anda ingin hapus data ini?", "Peringatan", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (confirm == JOptionPane.YES_OPTION) {
                db.aksi("DELETE FROM login WHERE nama_pengguna = '" + tabel_data.getValueAt(row, 0) + "'");
                JOptionPane.showMessageDialog(null, "Berhasil Menghapus", "Pemberitahuan", JOptionPane.INFORMATION_MESSAGE);
                Bariss();
            }
        }
    }//GEN-LAST:event_hapusActionPerformed

    private void nambah_karyawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nambah_karyawanActionPerformed
        // TODO add your handling code here:
        defaultform f = new defaultform(12, 0);
        f.setDimens(1086, 595);
        f.setComp(12, 0);
        login.showForm(f);
    }//GEN-LAST:event_nambah_karyawanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel data_karyawan;
    private project.CustomButtons hapus;
    private javax.swing.JScrollPane jScrollPane1;
    private project.CustomButtons nambah_karyawan;
    private project.CustomTable tabel_data;
    // End of variables declaration//GEN-END:variables
}
