/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package lala;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import log.login;
import menu.sidebar;
import project.koneksi;
import utama.defaultform;

/**
 *
 * @author ASUS
 */
public class data_barang1 extends javax.swing.JPanel {
    boolean drop = false;
    koneksi db = new koneksi();
    DefaultTableModel table = new DefaultTableModel();
    String role;


    /**
     * Creates new form data_barang1
     */
    public data_barang1() {
        initComponents();
        db.koneksi();
        this.role = role;
        setColumn();
        setRows();
    }
    
    public void setColumn() {
        
        table.addColumn("Kode Barang");
        table.addColumn("Nama Barang");
        table.addColumn("Stok Barang");
        table.addColumn("Harga");
        table.addColumn("Status");
        tabel_databarang1.setModel(table);
    }
    
    public void setRows() {
        table.setRowCount(0);
        ResultSet rs = db.ambilData("SELECT * FROM data_barang");
        try {
            while (rs.next()) {
                table.addRow(new Object[]{rs.getString("kode_barang"), rs.getString("nama_barang"), rs.getString("stok"), rs.getString("harga"), rs.getString("Status")});
            }
            tabel_databarang1.setModel(table);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        data_barang1 = new javax.swing.JPanel();
        customButton4 = new project.CustomButtons();
        tambah_barang = new project.CustomButtons();
        edit_barang = new project.CustomButtons();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_databarang1 = new project.CustomTable();

        data_barang1.setBackground(java.awt.SystemColor.controlHighlight);
        data_barang1.setPreferredSize(new java.awt.Dimension(1190, 640));
        data_barang1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        customButton4.setText("customButton2");
        customButton4.setBackgroundColor(new java.awt.Color(255, 0, 51));
        customButton4.setBorderRadius(25);
        customButton4.setTextBold(0);
        customButton4.setTextColor(java.awt.Color.white);
        customButton4.setTheText("Hapus");
        customButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customButton4ActionPerformed(evt);
            }
        });
        data_barang1.add(customButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 120, 40));

        tambah_barang.setText("customButton2");
        tambah_barang.setBackgroundColor(new java.awt.Color(25, 192, 236));
        tambah_barang.setBorderRadius(25);
        tambah_barang.setTextBold(0);
        tambah_barang.setTextColor(java.awt.Color.white);
        tambah_barang.setTheText("Tambah");
        tambah_barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tambah_barangMouseClicked(evt);
            }
        });
        tambah_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambah_barangActionPerformed(evt);
            }
        });
        data_barang1.add(tambah_barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 120, 40));

        edit_barang.setText("customButton2");
        edit_barang.setBackgroundColor(new java.awt.Color(25, 192, 236));
        edit_barang.setBorderRadius(25);
        edit_barang.setTextBold(0);
        edit_barang.setTextColor(java.awt.Color.white);
        edit_barang.setTheText("Edit");
        edit_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_barangActionPerformed(evt);
            }
        });
        data_barang1.add(edit_barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 120, 40));

        tabel_databarang1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_databarang1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                tabel_databarang1ComponentHidden(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_databarang1);

        data_barang1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 360));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(data_barang1, javax.swing.GroupLayout.PREFERRED_SIZE, 1096, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(data_barang1, javax.swing.GroupLayout.PREFERRED_SIZE, 704, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void customButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customButton4ActionPerformed
        // TODO add your handling code here:
        int row = tabel_databarang1.getSelectedRow();
        if (row != -1) {
            int confirm = JOptionPane.showConfirmDialog(null, "Apakah anda ingin hapus data ini?", "Peringatan", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (confirm == JOptionPane.YES_OPTION) {
                db.aksi("DELETE FROM data_barang WHERE kode_barang = '" + tabel_databarang1.getValueAt(row, 0) + "'");
                JOptionPane.showMessageDialog(null, "Berhasil Menghapus", "Pemberitahuan", JOptionPane.INFORMATION_MESSAGE);
                setRows();
            }
        }
    }//GEN-LAST:event_customButton4ActionPerformed

    private void tambah_barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambah_barangActionPerformed
        // TODO add your handling code here:
        defaultform f = new defaultform(10, 0);
        f.setDimens(1086, 595);
        f.setComp(10, 0);
        login.showForm(f);
    }//GEN-LAST:event_tambah_barangActionPerformed

    private void edit_barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_barangActionPerformed
        // TODO add your handling code here:
        int row = tabel_databarang1.getSelectedRow();
        defaultform f = new defaultform(10, 0);
        f.setDimens(1086, 595);
        f.setComp(10, String.valueOf(tabel_databarang1.getValueAt(row, 0)));
        login.showForm(f);
       
    }//GEN-LAST:event_edit_barangActionPerformed

    private void tabel_databarang1ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tabel_databarang1ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_tabel_databarang1ComponentHidden

    private void tambah_barangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tambah_barangMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tambah_barangMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private project.CustomButtons customButton4;
    private javax.swing.JPanel data_barang1;
    private project.CustomButtons edit_barang;
    private javax.swing.JScrollPane jScrollPane1;
    private project.CustomTable tabel_databarang1;
    private project.CustomButtons tambah_barang;
    // End of variables declaration//GEN-END:variables
}
