/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package lala;

import javax.swing.JOptionPane;
import log.login;
import project.koneksi;
import utama.defaultform;

/**
 *
 * @author ASUS
 */
public class nambah_karyawan extends javax.swing.JPanel {
    koneksi db = new koneksi();
    String role;

    /**
     * Creates new form nambah_karyawan
     */
    public nambah_karyawan() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nambah_karyawan = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        tambah_karyawan = new project.CustomButtons();
        telepon = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        batal = new project.CustomButtons();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        kelamin = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        role1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pw = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamat = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        btn_role = new javax.swing.JComboBox<>();

        nambah_karyawan.setBackground(new java.awt.Color(255, 255, 255));
        nambah_karyawan.setMinimumSize(new java.awt.Dimension(735, 380));
        nambah_karyawan.setPreferredSize(new java.awt.Dimension(1190, 640));
        nambah_karyawan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tambah_karyawan.setForeground(new java.awt.Color(255, 255, 255));
        tambah_karyawan.setBackgroundColor(new java.awt.Color(25, 192, 236));
        tambah_karyawan.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        tambah_karyawan.setLabel("tambah karyawan");
        tambah_karyawan.setName("tambah karyawan"); // NOI18N
        tambah_karyawan.setTextColor(java.awt.Color.white);
        tambah_karyawan.setTheText("Tambah");
        tambah_karyawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambah_karyawanActionPerformed(evt);
            }
        });
        jPanel3.add(tambah_karyawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 230, 100, 31));

        telepon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teleponActionPerformed(evt);
            }
        });
        jPanel3.add(telepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 270, 33));

        nama.setText("Masukkan nama");
        nama.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                namaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                namaFocusLost(evt);
            }
        });
        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });
        jPanel3.add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 270, 33));

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel3.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 270, 33));

        batal.setForeground(new java.awt.Color(255, 255, 255));
        batal.setText("Data jenis Laundry");
        batal.setBackgroundColor(new java.awt.Color(255, 0, 51));
        batal.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        batal.setName("Data jenis Laundry\n"); // NOI18N
        batal.setTextColor(java.awt.Color.white);
        batal.setTheText("Batal");
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });
        jPanel3.add(batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 270, 100, 30));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setText("Email");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 124, -1));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setText("Nama");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 124, -1));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel5.setText("Alamat");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 80, -1));

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel6.setText("Nomer Telepon");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 124, -1));

        kelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki laki", "Perempuan" }));
        kelamin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelaminActionPerformed(evt);
            }
        });
        jPanel3.add(kelamin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 270, 33));

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel9.setText("Jenis Kelamin");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 124, -1));

        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        jPanel3.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 270, 33));

        role1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        role1.setText("Role");
        jPanel3.add(role1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, 124, -1));

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel10.setText("Password");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 124, -1));

        pw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwActionPerformed(evt);
            }
        });
        jPanel3.add(pw, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 270, 33));

        alamat.setColumns(20);
        alamat.setRows(5);
        alamat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                alamatKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(alamat);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 270, -1));

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel11.setText("Username");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 124, -1));

        btn_role.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "staff" }));
        jPanel3.add(btn_role, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 50, 90, 30));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 600));

        nambah_karyawan.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nambah_karyawan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nambah_karyawan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void alamatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_alamatKeyReleased
        // TODO add your handling code here:
        if((evt.getKeyCode()==10)){
            btn_role.requestFocus();
        }
    }//GEN-LAST:event_alamatKeyReleased

    private void pwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwActionPerformed
        // TODO add your handling code here:
        alamat.requestFocus();
    }//GEN-LAST:event_pwActionPerformed

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:\
        pw.requestFocus();
    }//GEN-LAST:event_userActionPerformed

    private void kelaminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelaminActionPerformed
        // TODO add your handling code here:
        user.requestFocus();
    }//GEN-LAST:event_kelaminActionPerformed

    private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed
        // TODO add your handling code here:
        //data_karyawan db1 = new data_karyawan (role);
        //db1.setVisible(true);
        defaultform f = new defaultform(2, 0);
        f.setDimens(1086, 595);
        f.setComp(2, 0);
        login.showForm(f);
    }//GEN-LAST:event_batalActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
        telepon.requestFocus();
    }//GEN-LAST:event_emailActionPerformed

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
        email.requestFocus();
    }//GEN-LAST:event_namaActionPerformed

    private void namaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_namaFocusLost
        // TODO add your handling code here:
        String input=nama.getText();
        if(input.equals("")){
            nama.setText("Masukkan nama");
        }
    }//GEN-LAST:event_namaFocusLost

    private void namaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_namaFocusGained
        // TODO add your handling code here:
        String input=nama.getText();
        if(input.equals("Masukkan nama")){
            nama.setText("");
        }
    }//GEN-LAST:event_namaFocusGained

    private void teleponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teleponActionPerformed
        // TODO add your handling code here:
        kelamin.requestFocus();
    }//GEN-LAST:event_teleponActionPerformed

    private void tambah_karyawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambah_karyawanActionPerformed
        // TODO add your handling code here:
        db.aksi("INSERT INTO `login`(nama_pengguna,email,telepon,alamat,username,password,kelamin,role) VALUES ('"+nama.getText()+"','"
            +email.getText()+"','"+telepon.getText()+"','"+alamat.getText()+"','"+user.getText()+"','"
            +pw.getText()+"','"+kelamin.getSelectedItem()+"','"+btn_role.getSelectedItem()+"')");
        JOptionPane.showMessageDialog(null, "Tambah Berhasil", "Pemberitahuan", JOptionPane.INFORMATION_MESSAGE);
        // TODO add your handling code here:
        defaultform f = new defaultform(2, 0);
        f.setDimens(1086, 595);
        f.setComp(2, 0);
        login.showForm(f);
    }//GEN-LAST:event_tambah_karyawanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamat;
    private project.CustomButtons batal;
    private javax.swing.JComboBox<String> btn_role;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> kelamin;
    private javax.swing.JTextField nama;
    private javax.swing.JPanel nambah_karyawan;
    private javax.swing.JTextField pw;
    private javax.swing.JLabel role1;
    private project.CustomButtons tambah_karyawan;
    private javax.swing.JTextField telepon;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
