/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package lala;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.util.HashMap;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import log.login;
import project.koneksi;
import utama.defaultform;

/**
 *
 * @author ASUS
 */
public class tabel_pengeluaran extends javax.swing.JPanel {
    koneksi db = new koneksi();
    DefaultTableModel table = new DefaultTableModel();
    String role;
    HashMap<String, Integer> map = new HashMap<>();

    /**
     * Creates new form tabel_pengeluaran
     */
    public tabel_pengeluaran() {
        initComponents();
        aturBariss();
        setColumn();
        setRows();
        setCbTahun();
        this.role = role;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public void setRows() {
        table.setRowCount(0);
        ResultSet rs = db.ambilData("SELECT * FROM pengeluaran");
        try {
            while (rs.next()) {
                table.addRow(new Object[]{rs.getString("kode_pengeluaran"),
                    rs.getString("tanggal"), 
                    rs.getString("jenis_pengeluaran"),
                    rs.getString("total_pengeluaran"),
                    rs.getString("keterangan")});
                
            }
            tabel_pengeluaran.setModel(table);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    
     public void setCbTahun() {
        for(int i = 2019; i < 2035; i++) {
            tahun.addItem(String.valueOf(i));
        }
        map.put("Januari", 1);
        map.put("Februari", 2);
        map.put("Maret", 3);
        map.put("April", 4);
        map.put("Mei", 5);
        map.put("Juni", 6);
        map.put("Juli", 7);
        map.put("Agustus", 8);
        map.put("September", 9);
        map.put("Oktober", 10);
        map.put("November", 11);
        map.put("Desember", 12);
    }

    
    public void aturBariss(){
         table.setRowCount(0);
        ResultSet hasil = db.ambilData("SELECT * FROM pengeluaran;");
        try {
            while(hasil.next()) {
                table.addRow(new Object[]
                {   hasil.getString("kode_pengeluaran"),
                    hasil.getString("tanggal"),
                    hasil.getString("jenis_pengeluaran"), 
                    hasil.getString("total_pengeluaran"), 
                    hasil.getString("keterangan")});
            }
             tabel_pengeluaran.setModel(table);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    
    public void setColumn() {
        table.addColumn("Kode Pengeluaran");
        table.addColumn("Tanggal");
        table.addColumn("Jenis Pengeluaran");
        table.addColumn("Total");
        table.addColumn("Keterangan");
        tabel_pengeluaran.setModel(table);
    }
    
    public void setRowFromMonth(int month, String year) {
        table.setRowCount(0);
        ResultSet rs = db.ambilData("SELECT * FROM pengeluaran WHERE tanggal >= '" + year + "-" + month + "-01' AND tanggal <= '" + year + "-" + month + "-31'");
    try {
        while(rs.next()) {
            table.addRow(new Object[]
                {   rs.getString("kode_pengeluaran"),
                    rs.getString("tanggal"),
                    rs.getString("jenis_pengeluaran"), 
                    rs.getString("total_pengeluaran"), 
                    rs.getString("keterangan")});
            
             tabel_pengeluaran.setModel(table);
        }
    } catch (SQLException ex) {
        Logger.getLogger(project.Laporan.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
    
    public void setCbTgl() {
        HashMap<String, Integer> map = new HashMap<>();
        map.put("Januari", 31);
        map.put("Februari", 28);
        map.put("Maret", 31);
        map.put("April", 30);
        map.put("Mei", 31);
        map.put("Juni", 30);
        map.put("Juli", 31);
        map.put("Agustus", 31);
        map.put("September", 30);
        map.put("Oktober", 31);
        map.put("November", 30);
        map.put("Desember", 31);
        tanggal.removeAllItems();
        tanggal.addItem("Silahkan Pilih");
        try {
            if(!tahun.getSelectedItem().equals("--Tidak dipilih--") || !bulan.getSelectedItem().equals("Silahkan Pilih")) {
                int kabisat = Integer.parseInt(String.valueOf(tahun.getSelectedItem())) % 4;
                if(kabisat == 0 && bulan.getSelectedItem().equals("Februari")) {
                    for(int i = 0; i < map.get("Februari") + 1; i++) {
                        tanggal.addItem(String.valueOf(i + 1));
                    }
                } else {
                    for(int i = 0; i < map.get(String.valueOf(bulan.getSelectedItem())); i++) {
                        tanggal.addItem(String.valueOf(i + 1));
                    }
                }
            } else {
                // Hehe
            }
        } catch(Exception e) {
            System.err.println("Masukin dulu bulan atau tahun nya!");
        }
    }
    
    public String changeToNum(String num) {
        String result = "";
        for(int i = 0; i < num.replace('.', 'a').split("a").length; i++) {
            result += num.replace('.', 'a').split("a")[i];
        }
        return result;
    }
    
    public String changeToRp(String num) { 
        try {
            NumberFormat nf = NumberFormat.getInstance(new Locale("id", "ID"));
        return "Rp. " + nf.format(Double.parseDouble(num));
        } catch (Exception e) {
        }
            
        return "Rp. " + 0;
    }
    
    public void resetAll() {
        aturBariss();
        tabel_pengeluaran.setModel(table);
        pengeluaran_harian.setText("");
        pengeluaran_bulanan.setText("");
        pengeluaran_tahunan.setText("");
        tanggal.setSelectedItem("Tanggal");
        bulan.setSelectedItem("Bulan");
        tahun.setSelectedItem("Tahun");
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        bt_hapus = new project.CustomButtons();
        bt_tambah = new project.CustomButtons();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_pengeluaran = new project.CustomTable();
        jPanel7 = new javax.swing.JPanel();
        pengeluaran_harian = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        pngeluarn_har = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        pengeluaran_bulanan = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        pngeluarn_har1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        pngeluarn_har2 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        pengeluaran_tahunan = new javax.swing.JLabel();
        refresh = new javax.swing.JLabel();
        tanggal = new javax.swing.JComboBox<>();
        bulan = new javax.swing.JComboBox<>();
        tahun = new javax.swing.JComboBox<>();
        btn_oke = new project.CustomButtons();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1190, 640));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bt_hapus.setText("customButton2");
        bt_hapus.setBackgroundColor(new java.awt.Color(25, 192, 236));
        bt_hapus.setBorderRadius(25);
        bt_hapus.setTextBold(0);
        bt_hapus.setTextColor(java.awt.Color.white);
        bt_hapus.setTheText("Hapus");
        bt_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_hapusActionPerformed(evt);
            }
        });
        jPanel2.add(bt_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 500, 120, 30));

        bt_tambah.setText("customButton2");
        bt_tambah.setBackgroundColor(new java.awt.Color(25, 192, 236));
        bt_tambah.setBorderRadius(25);
        bt_tambah.setTextBold(0);
        bt_tambah.setTextColor(java.awt.Color.white);
        bt_tambah.setTheText("Tambah");
        bt_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_tambahActionPerformed(evt);
            }
        });
        jPanel2.add(bt_tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 500, 120, 30));

        tabel_pengeluaran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabel_pengeluaran);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 1050, 270));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pengeluaran_harian.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        pengeluaran_harian.setForeground(new java.awt.Color(25, 192, 236));
        pengeluaran_harian.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pengeluaran_harian.setText("Rp. 000.000");
        jPanel7.add(pengeluaran_harian, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 240, -1));

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 240, 80));

        jPanel3.setBackground(new java.awt.Color(25, 192, 236));

        pngeluarn_har.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        pngeluarn_har.setForeground(new java.awt.Color(255, 255, 255));
        pngeluarn_har.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pngeluarn_har.setText("Pengeluaran Harian");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pngeluarn_har, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pngeluarn_har)
                .addGap(69, 69, 69))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 40));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pengeluaran_bulanan.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        pengeluaran_bulanan.setForeground(new java.awt.Color(25, 192, 236));
        pengeluaran_bulanan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pengeluaran_bulanan.setText("Rp. 000.000");
        jPanel8.add(pengeluaran_bulanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 240, -1));

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, -1, 80));

        jPanel4.setBackground(new java.awt.Color(25, 192, 236));

        pngeluarn_har1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        pngeluarn_har1.setForeground(new java.awt.Color(255, 255, 255));
        pngeluarn_har1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pngeluarn_har1.setText("Pengeluaran Bulanan");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pngeluarn_har1, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pngeluarn_har1)
                .addGap(69, 69, 69))
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, -1, 40));

        jPanel5.setBackground(new java.awt.Color(25, 192, 236));

        pngeluarn_har2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        pngeluarn_har2.setForeground(new java.awt.Color(255, 255, 255));
        pngeluarn_har2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pngeluarn_har2.setText("Pengeluaran Tahunan");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pngeluarn_har2, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pngeluarn_har2)
                .addGap(69, 69, 69))
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, -1, 40));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pengeluaran_tahunan.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        pengeluaran_tahunan.setForeground(new java.awt.Color(25, 192, 236));
        pengeluaran_tahunan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pengeluaran_tahunan.setText("Rp. 000.000");
        jPanel9.add(pengeluaran_tahunan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 240, -1));

        jPanel2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 60, -1, 80));

        refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/refresh.png"))); // NOI18N
        refresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshMouseClicked(evt);
            }
        });
        jPanel2.add(refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, -1, -1));

        tanggal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tanggal" }));
        tanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanggalActionPerformed(evt);
            }
        });
        jPanel2.add(tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 170, 110, 30));

        bulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bulan", "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        bulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bulanActionPerformed(evt);
            }
        });
        jPanel2.add(bulan, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 170, 110, 30));

        tahun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tahun" }));
        tahun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tahunActionPerformed(evt);
            }
        });
        jPanel2.add(tahun, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 170, 110, 30));

        btn_oke.setText("customButtons1");
        btn_oke.setBackgroundColor(new java.awt.Color(25, 192, 236));
        btn_oke.setTextColor(java.awt.Color.white);
        btn_oke.setTheText("OK");
        btn_oke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_okeActionPerformed(evt);
            }
        });
        jPanel2.add(btn_oke, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 170, 50, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 660));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 832, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bt_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_hapusActionPerformed
        // TODO add your handling code here:
        int row = tabel_pengeluaran.getSelectedRow();
        if (row != -1) {
            int confirm = JOptionPane.showConfirmDialog(null, "Apakah anda ingin hapus data ini?", "Peringatan", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (confirm == JOptionPane.YES_OPTION) {
                db.aksi("DELETE FROM pengeluaran WHERE kode_pengeluaran = '" + tabel_pengeluaran.getValueAt(row, 0) + "'");
                JOptionPane.showMessageDialog(null, "Berhasil Menghapus", "Pemberitahuan", JOptionPane.INFORMATION_MESSAGE);
                setRows();
            }
        }
    }//GEN-LAST:event_bt_hapusActionPerformed

    private void bt_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_tambahActionPerformed
        // TODO add your handling code here:
        //db.aksi("INSERT INTO pengeluaran (kode_pengeluaran, jenis_pengeluaran, total_pengeluaran, keterangan) VALUES ('" + kode_pengeluaran.getText() + "', '" + jns_pengeluaran.getText()+ "', '" + total_pengeluaran1.getText() + "', '" + input_keterangan1.getText() + "')");
        //JOptionPane.showMessageDialog(null, "Tambah Berhasil", "Pemberitahuan", JOptionPane.INFORMATION_MESSAGE);
        //pengeluaran db1 = new pengeluaran(role);
        //db1.setVisible(true);
        //this.setVisible(false);
        defaultform f = new defaultform(15, 0);
        f.setDimens(1086, 595);
        f.setComp(15, 0);
        login.showForm(f);
    }//GEN-LAST:event_bt_tambahActionPerformed

    private void refreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshMouseClicked
        // TODO add your handling code here:
        resetAll();
    }//GEN-LAST:event_refreshMouseClicked

    private void tanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanggalActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_tanggalActionPerformed

    private void bulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bulanActionPerformed
        setCbTgl();
    }//GEN-LAST:event_bulanActionPerformed

    private void tahunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tahunActionPerformed
        // TODO add your handling code here:
        setCbTgl();
    }//GEN-LAST:event_tahunActionPerformed

    private void btn_okeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_okeActionPerformed
        // TODO add your handling code here:
        String tgl = tanggal.getSelectedItem().toString();
        String bln = bulan.getSelectedItem().toString();
        String thn = tahun.getSelectedItem().toString();
        ResultSet pemasukanharian = db.ambilData("SELECT SUM(total_pengeluaran) AS totalharga FROM pengeluaran WHERE tanggal = '" + thn + "-" + map.get(bln) + "-" + tgl + "'");
        ResultSet pemasukanbulanan = db.ambilData("SELECT SUM(total_pengeluaran) AS totalharga FROM pengeluaran WHERE tanggal >= '" + thn + "-" + map.get(bln) + "-01' AND tanggal <= '" + thn + "-" + map.get(bln) + "-31'");
        ResultSet pemasukantahunan = db.ambilData("SELECT SUM(total_pengeluaran) AS totalharga FROM pengeluaran WHERE tanggal >= '" + thn + "-01-01' AND tanggal <= '" + thn + "-12-31'");

        /*ResultSet pengeluaranarian = db.ambilData("SELECT SUM(harga) AS hehe FROM pengeluaran WHERE tanggal_pengeluaran = '" + thn + "-" + map.get(bln) + "-" + tgl + "'");
        ResultSet pengeluaranBulanan = db.ambilData("SELECT SUM(harga) AS hehe FROM pengeluaran WHERE tanggal_pengeluaran >= '" + thn + "-" + map.get(bln) + "-01' AND tgl_pengeluaran <= '" + thn + "-" + map.get(bln) + "-31'");
        ResultSet pengeluaranTahunan = db.ambilData("SELECT SUM(harga) AS hehe FROM pengeluaran WHERE tanggal_pengeluaran >= '" + thn + "-01-01' AND tgl_pengeluaran <= '" + thn + "-12-31'");*/
        try {
            if(pemasukanharian.next()) {
                pengeluaran_harian.setText(changeToRp(pemasukanharian.getString("totalharga")));
            } else {
                pengeluaran_harian.setText("Tidak ada Data!");
            }
            if(pemasukanbulanan.next()) {
                pengeluaran_bulanan.setText(changeToRp(pemasukanbulanan.getString("totalharga")));
            } else {
                pengeluaran_bulanan.setText("Tidak ada Data!");
            }
            if(pemasukantahunan.next()) {
                pengeluaran_tahunan.setText(changeToRp(pemasukantahunan.getString("totalharga")));
            } else {
                pengeluaran_tahunan.setText("Tidak ada Data!");
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        setRowFromMonth(map.get(bln), thn);
    }//GEN-LAST:event_btn_okeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private project.CustomButtons bt_hapus;
    private project.CustomButtons bt_tambah;
    private project.CustomButtons btn_oke;
    private javax.swing.JComboBox<String> bulan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel pengeluaran_bulanan;
    private javax.swing.JLabel pengeluaran_harian;
    private javax.swing.JLabel pengeluaran_tahunan;
    private javax.swing.JLabel pngeluarn_har;
    private javax.swing.JLabel pngeluarn_har1;
    private javax.swing.JLabel pngeluarn_har2;
    private javax.swing.JLabel refresh;
    private project.CustomTable tabel_pengeluaran;
    private javax.swing.JComboBox<String> tahun;
    private javax.swing.JComboBox<String> tanggal;
    // End of variables declaration//GEN-END:variables
}
